export { S0_Hook } from "./S0_Hook";
export { S1_Problema } from "./S1_Problema";
export { S2_CrearCaso } from "./S2_CrearCaso";
export { S3_Fauchard } from "./S3_Fauchard";
export { S4_Tecnico } from "./S4_Tecnico";
export { S5_Comparativo } from "./S5_Comparativo";
export { S6_Diseno } from "./S6_Diseno";
export { S7_Fabricacion } from "./S7_Fabricacion";
export { S8_Valor } from "./S8_Valor";
