steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'gcr.io/$PROJECT_ID/frontend:${_TAG}', '.']
substitutions:
  _TAG: latest
images:
  - 'gcr.io/$PROJECT_ID/frontend:${_TAG}'
