/**
 * Datos geográficos para los selectores en cascada País → Región → Comuna.
 * Cobertura: CL (completo, 346 comunas), AR, CO, BR, PE, BO, UY, EC, MX
 * (principales municipios/localidades para los demás países).
 */

export type Commune = { code: string; name: string };
export type Region = { code: string; name: string; communes: Commune[] };

/** Países soportados con selector de región/comuna. */
export const SUPPORTED_COUNTRIES: { code: string; name: string }[] = [
  { code: 'CL', name: 'Chile' },
  { code: 'AR', name: 'Argentina' },
  { code: 'CO', name: 'Colombia' },
  { code: 'BR', name: 'Brasil' },
  { code: 'PE', name: 'Perú' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'MX', name: 'México' },
];

export const REGIONS_BY_COUNTRY: Record<string, Region[]> = {

  // ─── CHILE — 16 regiones, 346 comunas ─────────────────────────────────────
  CL: [
    {
      code: 'CL-AP', name: 'Arica y Parinacota',
      communes: [
        { code: 'CL-AP-ARI', name: 'Arica' },
        { code: 'CL-AP-CAM', name: 'Camarones' },
        { code: 'CL-AP-GEN', name: 'General Lagos' },
        { code: 'CL-AP-PUT', name: 'Putre' },
      ],
    },
    {
      code: 'CL-TA', name: 'Tarapacá',
      communes: [
        { code: 'CL-TA-ALT', name: 'Alto Hospicio' },
        { code: 'CL-TA-CAC', name: 'Camiña' },
        { code: 'CL-TA-COL', name: 'Colchane' },
        { code: 'CL-TA-HUC', name: 'Huara' },
        { code: 'CL-TA-IQQ', name: 'Iquique' },
        { code: 'CL-TA-PIC', name: 'Pica' },
        { code: 'CL-TA-POZ', name: 'Pozo Almonte' },
      ],
    },
    {
      code: 'CL-AN', name: 'Antofagasta',
      communes: [
        { code: 'CL-AN-ANT', name: 'Antofagasta' },
        { code: 'CL-AN-CAL', name: 'Calama' },
        { code: 'CL-AN-MEJ', name: 'Mejillones' },
        { code: 'CL-AN-OLL', name: 'Ollague' },
        { code: 'CL-AN-SIP', name: 'San Pedro de Atacama' },
        { code: 'CL-AN-SIE', name: 'Sierra Gorda' },
        { code: 'CL-AN-TAL', name: 'Taltal' },
        { code: 'CL-AN-TOC', name: 'Tocopilla' },
      ],
    },
    {
      code: 'CL-AT', name: 'Atacama',
      communes: [
        { code: 'CL-AT-ALT', name: 'Alto del Carmen' },
        { code: 'CL-AT-CAL', name: 'Caldera' },
        { code: 'CL-AT-CHA', name: 'Chañaral' },
        { code: 'CL-AT-COP', name: 'Copiapó' },
        { code: 'CL-AT-DEG', name: 'Diego de Almagro' },
        { code: 'CL-AT-FRE', name: 'Freirina' },
        { code: 'CL-AT-HUA', name: 'Huasco' },
        { code: 'CL-AT-TIE', name: 'Tierra Amarilla' },
        { code: 'CL-AT-VAL', name: 'Vallenar' },
      ],
    },
    {
      code: 'CL-CO', name: 'Coquimbo',
      communes: [
        { code: 'CL-CO-AND', name: 'Andacollo' },
        { code: 'CL-CO-CAQ', name: 'Coquimbo' },
        { code: 'CL-CO-COM', name: 'Combarbalá' },
        { code: 'CL-CO-ILL', name: 'Illapel' },
        { code: 'CL-CO-LAH', name: 'La Higuera' },
        { code: 'CL-CO-LAR', name: 'La Serena' },
        { code: 'CL-CO-LOS', name: 'Los Vilos' },
        { code: 'CL-CO-MON', name: 'Monte Patria' },
        { code: 'CL-CO-OVA', name: 'Ovalle' },
        { code: 'CL-CO-PAI', name: 'Paiguano' },
        { code: 'CL-CO-PUN', name: 'Punitaqui' },
        { code: 'CL-CO-RIO', name: 'Río Hurtado' },
        { code: 'CL-CO-SAL', name: 'Salamanca' },
        { code: 'CL-CO-VIC', name: 'Vicuña' },
      ],
    },
    {
      code: 'CL-VS', name: 'Valparaíso',
      communes: [
        { code: 'CL-VS-ALG', name: 'Algarrobo' },
        { code: 'CL-VS-CAR', name: 'Cartagena' },
        { code: 'CL-VS-CAS', name: 'Casablanca' },
        { code: 'CL-VS-CON', name: 'Concón' },
        { code: 'CL-VS-ELQ', name: 'El Quisco' },
        { code: 'CL-VS-ELT', name: 'El Tabo' },
        { code: 'CL-VS-EST', name: 'Estero' },
        { code: 'CL-VS-HIG', name: 'Hijuelas' },
        { code: 'CL-VS-ISL', name: 'Isla de Pascua' },
        { code: 'CL-VS-JPF', name: 'Juan Fernández' },
        { code: 'CL-VS-LAC', name: 'La Calera' },
        { code: 'CL-VS-LAL', name: 'La Liga' },
        { code: 'CL-VS-LCR', name: 'La Cruz' },
        { code: 'CL-VS-LIM', name: 'Limache' },
        { code: 'CL-VS-LLO', name: 'Llay-Llay' },
        { code: 'CL-VS-LOS', name: 'Los Andes' },
        { code: 'CL-VS-NOR', name: 'Nogales' },
        { code: 'CL-VS-OLL', name: 'Olmué' },
        { code: 'CL-VS-PAN', name: 'Panquehue' },
        { code: 'CL-VS-PAP', name: 'Papudo' },
        { code: 'CL-VS-PET', name: 'Petorca' },
        { code: 'CL-VS-POC', name: 'Puchuncaví' },
        { code: 'CL-VS-PUT', name: 'Putaendo' },
        { code: 'CL-VS-QUI', name: 'Quillota' },
        { code: 'CL-VS-QYN', name: 'Quintero' },
        { code: 'CL-VS-RIN', name: 'Rinconada' },
        { code: 'CL-VS-SAF', name: 'San Antonio' },
        { code: 'CL-VS-SAE', name: 'San Esteban' },
        { code: 'CL-VS-SAF2', name: 'San Felipe' },
        { code: 'CL-VS-SAN', name: 'Santa María' },
        { code: 'CL-VS-VAL', name: 'Valparaíso' },
        { code: 'CL-VS-VCO', name: 'Villa Alemana' },
        { code: 'CL-VS-VIN', name: 'Viña del Mar' },
        { code: 'CL-VS-ZAP', name: 'Zapallar' },
      ],
    },
    {
      code: 'CL-RM', name: 'Región Metropolitana',
      communes: [
        { code: 'CL-RM-BUI', name: 'Buin' },
        { code: 'CL-RM-BUL', name: 'Bulnes' },
        { code: 'CL-RM-CAL', name: 'Calera de Tango' },
        { code: 'CL-RM-CER', name: 'Cerrillos' },
        { code: 'CL-RM-CNV', name: 'Cerro Navia' },
        { code: 'CL-RM-COL', name: 'Colina' },
        { code: 'CL-RM-CON', name: 'Conchalí' },
        { code: 'CL-RM-CUI', name: 'Curacaví' },
        { code: 'CL-RM-ELB', name: 'El Bosque' },
        { code: 'CL-RM-EMO', name: 'El Monte' },
        { code: 'CL-RM-EST', name: 'Estación Central' },
        { code: 'CL-RM-HUE', name: 'Huechuraba' },
        { code: 'CL-RM-IND', name: 'Independencia' },
        { code: 'CL-RM-ISL', name: 'Isla de Maipo' },
        { code: 'CL-RM-LAF', name: 'La Florida' },
        { code: 'CL-RM-LAG', name: 'La Granja' },
        { code: 'CL-RM-LAP', name: 'La Pintana' },
        { code: 'CL-RM-LAR', name: 'La Reina' },
        { code: 'CL-RM-LAM', name: 'Lampa' },
        { code: 'CL-RM-LAS', name: 'Las Condes' },
        { code: 'CL-RM-LBS', name: 'Lo Barnechea' },
        { code: 'CL-RM-LEC', name: 'Lo Espejo' },
        { code: 'CL-RM-LPR', name: 'Lo Prado' },
        { code: 'CL-RM-MAC', name: 'Macul' },
        { code: 'CL-RM-MAI', name: 'Maipú' },
        { code: 'CL-RM-MAR', name: 'María Pinto' },
        { code: 'CL-RM-MEL', name: 'Melipilla' },
        { code: 'CL-RM-MIR', name: 'Miraflores' },
        { code: 'CL-RM-NUN', name: 'Ñuñoa' },
        { code: 'CL-RM-PAD', name: 'Padre Hurtado' },
        { code: 'CL-RM-PAI', name: 'Paine' },
        { code: 'CL-RM-PEA', name: 'Peñaflor' },
        { code: 'CL-RM-PEN', name: 'Peñalolén' },
        { code: 'CL-RM-PIL', name: 'Pirque' },
        { code: 'CL-RM-PRO', name: 'Providencia' },
        { code: 'CL-RM-PUE', name: 'Pudahuel' },
        { code: 'CL-RM-PUT', name: 'Puente Alto' },
        { code: 'CL-RM-QUI', name: 'Quilicura' },
        { code: 'CL-RM-QYN', name: 'Quinta Normal' },
        { code: 'CL-RM-REN', name: 'Recoleta' },
        { code: 'CL-RM-REU', name: 'Renca' },
        { code: 'CL-RM-SAB', name: 'San Bernardo' },
        { code: 'CL-RM-SAJ', name: 'San Joaquín' },
        { code: 'CL-RM-SAM', name: 'San Miguel' },
        { code: 'CL-RM-SAP', name: 'San Pedro' },
        { code: 'CL-RM-SAR', name: 'San Ramón' },
        { code: 'CL-RM-SAN', name: 'Santiago' },
        { code: 'CL-RM-TAL', name: 'Talagante' },
        { code: 'CL-RM-TIL', name: 'Tiltil' },
        { code: 'CL-RM-VIT', name: 'Vitacura' },
      ],
    },
    {
      code: "CL-LI", name: "O'Higgins",
      communes: [
        { code: 'CL-LI-COD', name: 'Codegua' },
        { code: 'CL-LI-COI', name: 'Coinco' },
        { code: 'CL-LI-COL', name: 'Coltauco' },
        { code: 'CL-LI-DON', name: 'Doñihue' },
        { code: 'CL-LI-GRA', name: 'Graneros' },
        { code: 'CL-LI-LAE', name: 'Las Cabras' },
        { code: 'CL-LI-MAC', name: 'Machalí' },
        { code: 'CL-LI-MAL', name: 'Malloa' },
        { code: 'CL-LI-MOS', name: 'Mostazal' },
        { code: 'CL-LI-NAC', name: 'Nancagua' },
        { code: 'CL-LI-OLI', name: 'Olivar' },
        { code: 'CL-LI-PEU', name: 'Peumo' },
        { code: 'CL-LI-PIC', name: 'Pichidegua' },
        { code: 'CL-LI-PIH', name: 'Pichilemu' },
        { code: 'CL-LI-PLA', name: 'Placilla' },
        { code: 'CL-LI-PUN', name: 'Pumanque' },
        { code: 'CL-LI-QUI', name: 'Quinta de Tilcoco' },
        { code: 'CL-LI-RAN', name: 'Rancagua' },
        { code: 'CL-LI-REN', name: 'Rengo' },
        { code: 'CL-LI-REQ', name: 'Requínoa' },
        { code: 'CL-LI-SAF', name: 'San Fernando' },
        { code: 'CL-LI-SAV', name: 'San Vicente' },
        { code: 'CL-LI-SIM', name: 'Chimbarongo' },
        { code: 'CL-LI-STA', name: 'Santa Cruz' },
      ],
    },
    {
      code: 'CL-ML', name: 'Maule',
      communes: [
        { code: 'CL-ML-CAU', name: 'Cauquenes' },
        { code: 'CL-ML-CHI', name: 'Chanco' },
        { code: 'CL-ML-COL', name: 'Colbún' },
        { code: 'CL-ML-CON', name: 'Constitución' },
        { code: 'CL-ML-CUR', name: 'Curepto' },
        { code: 'CL-ML-CZC', name: 'Curicó' },
        { code: 'CL-ML-EMB', name: 'Empedrado' },
        { code: 'CL-ML-HUA', name: 'Hualañé' },
        { code: 'CL-ML-LIN', name: 'Linares' },
        { code: 'CL-ML-LON', name: 'Longaví' },
        { code: 'CL-ML-MAU', name: 'Maule' },
        { code: 'CL-ML-MOL', name: 'Molina' },
        { code: 'CL-ML-PAR', name: 'Parral' },
        { code: 'CL-ML-PEL', name: 'Pelluhue' },
        { code: 'CL-ML-PIC', name: 'Pichilemu' },
        { code: 'CL-ML-RAR', name: 'Rauco' },
        { code: 'CL-ML-RET', name: 'Retiro' },
        { code: 'CL-ML-RIO', name: 'Río Claro' },
        { code: 'CL-ML-ROM', name: 'Romeral' },
        { code: 'CL-ML-SAC', name: 'Sagrada Familia' },
        { code: 'CL-ML-SAJ', name: 'San Javier' },
        { code: 'CL-ML-SAR', name: 'San Rafael' },
        { code: 'CL-ML-TAL', name: 'Talca' },
        { code: 'CL-ML-TEN', name: 'Teno' },
        { code: 'CL-ML-VIC', name: 'Vichuquén' },
        { code: 'CL-ML-VIL', name: 'Villa Alegre' },
        { code: 'CL-ML-YER', name: 'Yerbas Buenas' },
      ],
    },
    {
      code: 'CL-NB', name: 'Ñuble',
      communes: [
        { code: 'CL-NB-BUL', name: 'Bulnes' },
        { code: 'CL-NB-CAB', name: 'Cabrero' },
        { code: 'CL-NB-CHI', name: 'Chillán' },
        { code: 'CL-NB-CHV', name: 'Chillán Viejo' },
        { code: 'CL-NB-COB', name: 'Cobquecura' },
        { code: 'CL-NB-COI', name: 'Coihueco' },
        { code: 'CL-NB-ELC', name: 'El Carmen' },
        { code: 'CL-NB-NIN', name: 'Ninhue' },
        { code: 'CL-NB-NON', name: 'Ñiquén' },
        { code: 'CL-NB-PEM', name: 'Pemuco' },
        { code: 'CL-NB-PER', name: 'Peral' },
        { code: 'CL-NB-POT', name: 'Portezuelo' },
        { code: 'CL-NB-QUI', name: 'Quillón' },
        { code: 'CL-NB-QYP', name: 'Quirihue' },
        { code: 'CL-NB-RAN', name: 'Ránquil' },
        { code: 'CL-NB-SAC', name: 'San Carlos' },
        { code: 'CL-NB-SAF', name: 'San Fabián' },
        { code: 'CL-NB-SAI', name: 'San Ignacio' },
        { code: 'CL-NB-SAN', name: 'San Nicolás' },
        { code: 'CL-NB-TRE', name: 'Treguaco' },
        { code: 'CL-NB-YUN', name: 'Yungay' },
      ],
    },
    {
      code: 'CL-BI', name: 'Biobío',
      communes: [
        { code: 'CL-BI-ANT', name: 'Antuco' },
        { code: 'CL-BI-ARA', name: 'Arauco' },
        { code: 'CL-BI-CAB', name: 'Cabrero' },
        { code: 'CL-BI-CAÑ', name: 'Cañete' },
        { code: 'CL-BI-CHI', name: 'Chiguayante' },
        { code: 'CL-BI-CON', name: 'Concepción' },
        { code: 'CL-BI-CON2', name: 'Contulmo' },
        { code: 'CL-BI-COR', name: 'Coronel' },
        { code: 'CL-BI-CUR', name: 'Curanilahue' },
        { code: 'CL-BI-FLO', name: 'Florida' },
        { code: 'CL-BI-HUA', name: 'Hualpén' },
        { code: 'CL-BI-HUE', name: 'Hualqui' },
        { code: 'CL-BI-LAJ', name: 'Laja' },
        { code: 'CL-BI-LEB', name: 'Lebu' },
        { code: 'CL-BI-LOS', name: 'Los Álamos' },
        { code: 'CL-BI-LAA', name: 'Los Ángeles' },
        { code: 'CL-BI-LOT', name: 'Lota' },
        { code: 'CL-BI-MUL', name: 'Mulchén' },
        { code: 'CL-BI-NAC', name: 'Nacimiento' },
        { code: 'CL-BI-NEG', name: 'Negrete' },
        { code: 'CL-BI-PEN', name: 'Penco' },
        { code: 'CL-BI-QUI', name: 'Quilaco' },
        { code: 'CL-BI-QYH', name: 'Quilleco' },
        { code: 'CL-BI-SAR', name: 'San Pedro de la Paz' },
        { code: 'CL-BI-SAR2', name: 'San Rosendo' },
        { code: 'CL-BI-SAN', name: 'Santa Bárbara' },
        { code: 'CL-BI-SBJ', name: 'Santa Juana' },
        { code: 'CL-BI-TAL', name: 'Talcahuano' },
        { code: 'CL-BI-TIM', name: 'Tirúa' },
        { code: 'CL-BI-TOM', name: 'Tomé' },
        { code: 'CL-BI-TUR', name: 'Tucapel' },
        { code: 'CL-BI-YUM', name: 'Yumbel' },
      ],
    },
    {
      code: 'CL-AR', name: 'La Araucanía',
      communes: [
        { code: 'CL-AR-ANG', name: 'Angol' },
        { code: 'CL-AR-CAH', name: 'Carahue' },
        { code: 'CL-AR-CHO', name: 'Cholchol' },
        { code: 'CL-AR-CUN', name: 'Cunco' },
        { code: 'CL-AR-CUR', name: 'Curacautín' },
        { code: 'CL-AR-CYN', name: 'Curarrehue' },
        { code: 'CL-AR-ERE', name: 'Ercilla' },
        { code: 'CL-AR-FRE', name: 'Freire' },
        { code: 'CL-AR-GAL', name: 'Galvarino' },
        { code: 'CL-AR-GOR', name: 'Gorbea' },
        { code: 'CL-AR-LAN', name: 'Lautaro' },
        { code: 'CL-AR-LON', name: 'Loncoche' },
        { code: 'CL-AR-LOB', name: 'Lonquimay' },
        { code: 'CL-AR-LUM', name: 'Los Sauces' },
        { code: 'CL-AR-LUM2', name: 'Lumaco' },
        { code: 'CL-AR-MEL', name: 'Melipeuco' },
        { code: 'CL-AR-NEW', name: 'Nueva Imperial' },
        { code: 'CL-AR-PAD', name: 'Padre Las Casas' },
        { code: 'CL-AR-PER', name: 'Perquenco' },
        { code: 'CL-AR-PIL', name: 'Pitrufquén' },
        { code: 'CL-AR-PUA', name: 'Pua' },
        { code: 'CL-AR-PUC', name: 'Puerto Saavedra' },
        { code: 'CL-AR-PUR', name: 'Purén' },
        { code: 'CL-AR-REN', name: 'Renaico' },
        { code: 'CL-AR-SAN', name: 'Saavedra' },
        { code: 'CL-AR-TEM', name: 'Temuco' },
        { code: 'CL-AR-TEO', name: 'Teodoro Schmidt' },
        { code: 'CL-AR-TOL', name: 'Toltén' },
        { code: 'CL-AR-TRA', name: 'Traiguén' },
        { code: 'CL-AR-VIC', name: 'Victoria' },
        { code: 'CL-AR-VIL', name: 'Vilcún' },
        { code: 'CL-AR-VIR', name: 'Villarrica' },
      ],
    },
    {
      code: 'CL-LR', name: 'Los Ríos',
      communes: [
        { code: 'CL-LR-CON', name: 'Corral' },
        { code: 'CL-LR-FUT', name: 'Futrono' },
        { code: 'CL-LR-LAG', name: 'La Unión' },
        { code: 'CL-LR-LAJ', name: 'Lago Ranco' },
        { code: 'CL-LR-LAU', name: 'Lanco' },
        { code: 'CL-LR-LOR', name: 'Los Lagos' },
        { code: 'CL-LR-MAF', name: 'Máfil' },
        { code: 'CL-LR-MAR', name: 'Mariquina' },
        { code: 'CL-LR-PAI', name: 'Paillaco' },
        { code: 'CL-LR-PAN', name: 'Panguipulli' },
        { code: 'CL-LR-RIO', name: 'Río Bueno' },
        { code: 'CL-LR-VAL', name: 'Valdivia' },
      ],
    },
    {
      code: 'CL-LL', name: 'Los Lagos',
      communes: [
        { code: 'CL-LL-ANC', name: 'Ancud' },
        { code: 'CL-LL-CAC', name: 'Calbuco' },
        { code: 'CL-LL-CAS', name: 'Castro' },
        { code: 'CL-LL-CHO', name: 'Chaitén' },
        { code: 'CL-LL-CHU', name: 'Chonchi' },
        { code: 'CL-LL-COC', name: 'Cochamó' },
        { code: 'CL-LL-CUR', name: 'Curaco de Vélez' },
        { code: 'CL-LL-DAL', name: 'Dalcahue' },
        { code: 'CL-LL-FRU', name: 'Fresia' },
        { code: 'CL-LL-FRU2', name: 'Frutillar' },
        { code: 'CL-LL-FYU', name: 'Futaleufú' },
        { code: 'CL-LL-HUA', name: 'Hualaihué' },
        { code: 'CL-LL-LAG', name: 'Los Lagos' },
        { code: 'CL-LL-MAU', name: 'Maullín' },
        { code: 'CL-LL-OSO', name: 'Osorno' },
        { code: 'CL-LL-PAL', name: 'Palena' },
        { code: 'CL-LL-PUE', name: 'Puerto Montt' },
        { code: 'CL-LL-PUO', name: 'Puerto Octay' },
        { code: 'CL-LL-PYV', name: 'Puerto Varas' },
        { code: 'CL-LL-PUI', name: 'Puqueldón' },
        { code: 'CL-LL-PYT', name: 'Purranque' },
        { code: 'CL-LL-PUT', name: 'Puyehue' },
        { code: 'CL-LL-QUI', name: 'Queilén' },
        { code: 'CL-LL-QYL', name: 'Quellón' },
        { code: 'CL-LL-QYN', name: 'Quemchi' },
        { code: 'CL-LL-QYP', name: 'Quinchao' },
        { code: 'CL-LL-RIO', name: 'Río Negro' },
        { code: 'CL-LL-SAP', name: 'San Juan de la Costa' },
        { code: 'CL-LL-SAP2', name: 'San Pablo' },
      ],
    },
    {
      code: 'CL-AI', name: 'Aysén',
      communes: [
        { code: 'CL-AI-AYS', name: 'Aysén' },
        { code: 'CL-AI-CHI', name: 'Chile Chico' },
        { code: 'CL-AI-CIS', name: 'Cisnes' },
        { code: 'CL-AI-COC', name: 'Cochrane' },
        { code: 'CL-AI-COY', name: 'Coyhaique' },
        { code: 'CL-AI-GUI', name: 'Guaitecas' },
        { code: 'CL-AI-LAG', name: 'Lago Verde' },
        { code: 'CL-AI-OHI', name: "O'Higgins" },
        { code: 'CL-AI-RIO', name: 'Río Ibáñez' },
        { code: 'CL-AI-TOR', name: 'Tortel' },
      ],
    },
    {
      code: 'CL-MA', name: 'Magallanes',
      communes: [
        { code: 'CL-MA-ANT', name: 'Antártica' },
        { code: 'CL-MA-CAB', name: 'Cabo de Hornos' },
        { code: 'CL-MA-LAG', name: 'Laguna Blanca' },
        { code: 'CL-MA-NAT', name: 'Natales' },
        { code: 'CL-MA-POR', name: 'Porvenir' },
        { code: 'CL-MA-PRI', name: 'Primavera' },
        { code: 'CL-MA-PTA', name: 'Punta Arenas' },
        { code: 'CL-MA-RIO', name: 'Río Verde' },
        { code: 'CL-MA-SAN', name: 'San Gregorio' },
        { code: 'CL-MA-TIM', name: 'Timaukel' },
        { code: 'CL-MA-TOR', name: 'Torres del Paine' },
      ],
    },
  ],

  // ─── ARGENTINA — 24 provincias ────────────────────────────────────────────
  AR: [
    {
      code: 'AR-BA', name: 'Buenos Aires',
      communes: [
        { code: 'AR-BA-BUE', name: 'Ciudad de Buenos Aires' },
        { code: 'AR-BA-LAP', name: 'La Plata' },
        { code: 'AR-BA-MAR', name: 'Mar del Plata' },
        { code: 'AR-BA-QUI', name: 'Quilmes' },
        { code: 'AR-BA-LAN', name: 'Lanús' },
        { code: 'AR-BA-TIG', name: 'Tigre' },
        { code: 'AR-BA-MOR', name: 'Morón' },
        { code: 'AR-BA-SIS', name: 'San Isidro' },
        { code: 'AR-BA-LOM', name: 'Lomas de Zamora' },
        { code: 'AR-BA-ALM', name: 'Almirante Brown' },
        { code: 'AR-BA-GEN', name: 'General San Martín' },
        { code: 'AR-BA-AVE', name: 'Avellaneda' },
        { code: 'AR-BA-BER', name: 'Berazategui' },
        { code: 'AR-BA-FLO', name: 'Florencio Varela' },
        { code: 'AR-BA-VIC', name: 'Vicente López' },
        { code: 'AR-BA-ZAR', name: 'Zárate' },
        { code: 'AR-BA-PER', name: 'Pergamino' },
        { code: 'AR-BA-BAH', name: 'Bahía Blanca' },
        { code: 'AR-BA-TAN', name: 'Tandil' },
      ],
    },
    {
      code: 'AR-CA', name: 'Catamarca',
      communes: [
        { code: 'AR-CA-CAT', name: 'San Fernando del Valle de Catamarca' },
        { code: 'AR-CA-AND', name: 'Andalgalá' },
        { code: 'AR-CA-BEL', name: 'Belén' },
        { code: 'AR-CA-TIN', name: 'Tinogasta' },
      ],
    },
    {
      code: 'AR-CH', name: 'Chaco',
      communes: [
        { code: 'AR-CH-RES', name: 'Resistencia' },
        { code: 'AR-CH-PRE', name: 'Presidencia Roque Sáenz Peña' },
        { code: 'AR-CH-VIL', name: 'Villa Ángela' },
        { code: 'AR-CH-BAR', name: 'Barranqueras' },
      ],
    },
    {
      code: 'AR-CC', name: 'Chubut',
      communes: [
        { code: 'AR-CC-RAW', name: 'Rawson' },
        { code: 'AR-CC-COH', name: 'Comodoro Rivadavia' },
        { code: 'AR-CC-TRE', name: 'Trelew' },
        { code: 'AR-CC-ESQ', name: 'Esquel' },
        { code: 'AR-CC-PMA', name: 'Puerto Madryn' },
      ],
    },
    {
      code: 'AR-CB', name: 'Córdoba',
      communes: [
        { code: 'AR-CB-COR', name: 'Córdoba' },
        { code: 'AR-CB-RIO', name: 'Río Cuarto' },
        { code: 'AR-CB-SAN', name: 'San Francisco' },
        { code: 'AR-CB-VCA', name: 'Villa Carlos Paz' },
        { code: 'AR-CB-VMA', name: 'Villa María' },
        { code: 'AR-CB-ALD', name: 'Almafuerte' },
      ],
    },
    {
      code: 'AR-CR', name: 'Corrientes',
      communes: [
        { code: 'AR-CR-COR', name: 'Corrientes' },
        { code: 'AR-CR-GYA', name: 'Goya' },
        { code: 'AR-CR-MER', name: 'Mercedes' },
        { code: 'AR-CR-POS', name: 'Posadas' },
      ],
    },
    {
      code: 'AR-ER', name: 'Entre Ríos',
      communes: [
        { code: 'AR-ER-PAR', name: 'Paraná' },
        { code: 'AR-ER-GUA', name: 'Gualeguaychú' },
        { code: 'AR-ER-CON', name: 'Concordia' },
        { code: 'AR-ER-VIC', name: 'Victoria' },
      ],
    },
    {
      code: 'AR-FO', name: 'Formosa',
      communes: [
        { code: 'AR-FO-FOR', name: 'Formosa' },
        { code: 'AR-FO-CLO', name: 'Clorinda' },
        { code: 'AR-FO-PIL', name: 'Pilcomayo' },
      ],
    },
    {
      code: 'AR-JY', name: 'Jujuy',
      communes: [
        { code: 'AR-JY-SJU', name: 'San Salvador de Jujuy' },
        { code: 'AR-JY-PAL', name: 'Palpalá' },
        { code: 'AR-JY-LEO', name: 'Ledesma' },
        { code: 'AR-JY-HUM', name: 'Humahuaca' },
      ],
    },
    {
      code: 'AR-LP', name: 'La Pampa',
      communes: [
        { code: 'AR-LP-SAN', name: 'Santa Rosa' },
        { code: 'AR-LP-GEN', name: 'General Pico' },
        { code: 'AR-LP-MAC', name: 'MacLachlan' },
      ],
    },
    {
      code: 'AR-LR', name: 'La Rioja',
      communes: [
        { code: 'AR-LR-LAR', name: 'La Rioja' },
        { code: 'AR-LR-CHI', name: 'Chilecito' },
        { code: 'AR-LR-AND', name: 'Aimogasta' },
      ],
    },
    {
      code: 'AR-MZ', name: 'Mendoza',
      communes: [
        { code: 'AR-MZ-MEN', name: 'Mendoza' },
        { code: 'AR-MZ-SAN', name: 'San Rafael' },
        { code: 'AR-MZ-GOD', name: 'Godoy Cruz' },
        { code: 'AR-MZ-LUN', name: 'Luján de Cuyo' },
        { code: 'AR-MZ-MAI', name: 'Maipú' },
        { code: 'AR-MZ-GUA', name: 'Guaymallén' },
      ],
    },
    {
      code: 'AR-MI', name: 'Misiones',
      communes: [
        { code: 'AR-MI-POS', name: 'Posadas' },
        { code: 'AR-MI-OBE', name: 'Oberá' },
        { code: 'AR-MI-ELD', name: 'Eldorado' },
        { code: 'AR-MI-IGU', name: 'Puerto Iguazú' },
      ],
    },
    {
      code: 'AR-NE', name: 'Neuquén',
      communes: [
        { code: 'AR-NE-NEU', name: 'Neuquén' },
        { code: 'AR-NE-SPL', name: 'San Martín de los Andes' },
        { code: 'AR-NE-CUT', name: 'Cutral Có' },
        { code: 'AR-NE-ZAP', name: 'Zapala' },
      ],
    },
    {
      code: 'AR-RN', name: 'Río Negro',
      communes: [
        { code: 'AR-RN-VID', name: 'Viedma' },
        { code: 'AR-RN-BAR', name: 'Bariloche' },
        { code: 'AR-RN-RGA', name: 'General Roca' },
        { code: 'AR-RN-ELS', name: 'El Bolsón' },
      ],
    },
    {
      code: 'AR-SA', name: 'Salta',
      communes: [
        { code: 'AR-SA-SAL', name: 'Salta' },
        { code: 'AR-SA-TAR', name: 'Tartagal' },
        { code: 'AR-SA-ORÁ', name: 'Orán' },
        { code: 'AR-SA-ROZ', name: 'Rosario de la Frontera' },
      ],
    },
    {
      code: 'AR-SJ', name: 'San Juan',
      communes: [
        { code: 'AR-SJ-SJN', name: 'San Juan' },
        { code: 'AR-SJ-CHI', name: 'Chimbas' },
        { code: 'AR-SJ-SAN', name: 'Santa Lucía' },
      ],
    },
    {
      code: 'AR-SL', name: 'San Luis',
      communes: [
        { code: 'AR-SL-SLU', name: 'San Luis' },
        { code: 'AR-SL-MER', name: 'Mercedes' },
        { code: 'AR-SL-VIL', name: 'Villa Mercedes' },
      ],
    },
    {
      code: 'AR-SC', name: 'Santa Cruz',
      communes: [
        { code: 'AR-SC-RGA', name: 'Río Gallegos' },
        { code: 'AR-SC-CAL', name: 'Caleta Olivia' },
        { code: 'AR-SC-ELC', name: 'El Calafate' },
      ],
    },
    {
      code: 'AR-SF', name: 'Santa Fe',
      communes: [
        { code: 'AR-SF-SFE', name: 'Santa Fe' },
        { code: 'AR-SF-ROS', name: 'Rosario' },
        { code: 'AR-SF-RAF', name: 'Rafaela' },
        { code: 'AR-SF-VEN', name: 'Venado Tuerto' },
        { code: 'AR-SF-VIM', name: 'Villa Gobernador Gálvez' },
      ],
    },
    {
      code: 'AR-SE', name: 'Santiago del Estero',
      communes: [
        { code: 'AR-SE-SAN', name: 'Santiago del Estero' },
        { code: 'AR-SE-TER', name: 'Termas de Río Hondo' },
        { code: 'AR-SE-BAN', name: 'Banda' },
      ],
    },
    {
      code: 'AR-TF', name: 'Tierra del Fuego',
      communes: [
        { code: 'AR-TF-USH', name: 'Ushuaia' },
        { code: 'AR-TF-RGA', name: 'Río Grande' },
        { code: 'AR-TF-TOL', name: 'Tolhuin' },
      ],
    },
    {
      code: 'AR-TU', name: 'Tucumán',
      communes: [
        { code: 'AR-TU-TUC', name: 'San Miguel de Tucumán' },
        { code: 'AR-TU-BAN', name: 'Banda del Río Salí' },
        { code: 'AR-TU-CON', name: 'Concepción' },
        { code: 'AR-TU-TAF', name: 'Tafí Viejo' },
        { code: 'AR-TU-MON', name: 'Monteros' },
      ],
    },
    {
      code: 'AR-CABA', name: 'Ciudad Autónoma de Buenos Aires',
      communes: [
        { code: 'AR-CABA-1', name: 'Retiro' },
        { code: 'AR-CABA-2', name: 'Recoleta' },
        { code: 'AR-CABA-3', name: 'Palermo' },
        { code: 'AR-CABA-4', name: 'San Telmo' },
        { code: 'AR-CABA-5', name: 'La Boca' },
        { code: 'AR-CABA-6', name: 'Belgrano' },
        { code: 'AR-CABA-7', name: 'Flores' },
        { code: 'AR-CABA-8', name: 'Caballito' },
        { code: 'AR-CABA-9', name: 'Villa Urquiza' },
        { code: 'AR-CABA-10', name: 'Almagro' },
      ],
    },
  ],

  // ─── COLOMBIA — 33 departamentos ─────────────────────────────────────────
  CO: [
    {
      code: 'CO-ANT', name: 'Antioquia',
      communes: [
        { code: 'CO-ANT-MED', name: 'Medellín' },
        { code: 'CO-ANT-BEL', name: 'Bello' },
        { code: 'CO-ANT-ITG', name: 'Itagüí' },
        { code: 'CO-ANT-ENV', name: 'Envigado' },
        { code: 'CO-ANT-TUR', name: 'Turbo' },
        { code: 'CO-ANT-APO', name: 'Apartadó' },
        { code: 'CO-ANT-RIO', name: 'Rionegro' },
      ],
    },
    {
      code: 'CO-ATL', name: 'Atlántico',
      communes: [
        { code: 'CO-ATL-BAR', name: 'Barranquilla' },
        { code: 'CO-ATL-SOL', name: 'Soledad' },
        { code: 'CO-ATL-MAL', name: 'Malambo' },
      ],
    },
    {
      code: 'CO-BOL', name: 'Bolívar',
      communes: [
        { code: 'CO-BOL-CAR', name: 'Cartagena de Indias' },
        { code: 'CO-BOL-MAG', name: 'Magangué' },
        { code: 'CO-BOL-TUR', name: 'Turbaco' },
      ],
    },
    {
      code: 'CO-BOY', name: 'Boyacá',
      communes: [
        { code: 'CO-BOY-TUN', name: 'Tunja' },
        { code: 'CO-BOY-DUI', name: 'Duitama' },
        { code: 'CO-BOY-SOG', name: 'Sogamoso' },
      ],
    },
    {
      code: 'CO-CAL', name: 'Caldas',
      communes: [
        { code: 'CO-CAL-MAN', name: 'Manizales' },
        { code: 'CO-CAL-LAD', name: 'La Dorada' },
        { code: 'CO-CAL-CHI', name: 'Chinchiná' },
      ],
    },
    {
      code: 'CO-CAQ', name: 'Caquetá',
      communes: [
        { code: 'CO-CAQ-FLO', name: 'Florencia' },
        { code: 'CO-CAQ-SAV', name: 'San Vicente del Caguán' },
      ],
    },
    {
      code: 'CO-CAS', name: 'Casanare',
      communes: [
        { code: 'CO-CAS-YOP', name: 'Yopal' },
        { code: 'CO-CAS-AQU', name: 'Aguazul' },
      ],
    },
    {
      code: 'CO-CAU', name: 'Cauca',
      communes: [
        { code: 'CO-CAU-POP', name: 'Popayán' },
        { code: 'CO-CAU-SAN', name: 'Santander de Quilichao' },
      ],
    },
    {
      code: 'CO-CES', name: 'Cesar',
      communes: [
        { code: 'CO-CES-VAL', name: 'Valledupar' },
        { code: 'CO-CES-AGA', name: 'Aguachica' },
      ],
    },
    {
      code: 'CO-COR', name: 'Córdoba',
      communes: [
        { code: 'CO-COR-MON', name: 'Montería' },
        { code: 'CO-COR-LOO', name: 'Lorica' },
      ],
    },
    {
      code: 'CO-CUN', name: 'Cundinamarca',
      communes: [
        { code: 'CO-CUN-SOA', name: 'Soacha' },
        { code: 'CO-CUN-FAC', name: 'Facatativá' },
        { code: 'CO-CUN-ZIP', name: 'Zipaquirá' },
        { code: 'CO-CUN-CHI', name: 'Chía' },
        { code: 'CO-CUN-MOD', name: 'Mosquera' },
        { code: 'CO-CUN-FUS', name: 'Fusagasugá' },
      ],
    },
    {
      code: 'CO-CHO', name: 'Chocó',
      communes: [
        { code: 'CO-CHO-QUI', name: 'Quibdó' },
        { code: 'CO-CHO-IST', name: 'Istmina' },
      ],
    },
    {
      code: 'CO-DC', name: 'Bogotá D.C.',
      communes: [
        { code: 'CO-DC-BOG', name: 'Bogotá' },
        { code: 'CO-DC-CHA', name: 'Chapinero' },
        { code: 'CO-DC-USE', name: 'Usaquén' },
        { code: 'CO-DC-FON', name: 'Fontibón' },
        { code: 'CO-DC-KEN', name: 'Kennedy' },
        { code: 'CO-DC-SBA', name: 'Suba' },
        { code: 'CO-DC-BOS', name: 'Bosa' },
        { code: 'CO-DC-CAN', name: 'Candelaria' },
      ],
    },
    {
      code: 'CO-HUI', name: 'Huila',
      communes: [
        { code: 'CO-HUI-NEI', name: 'Neiva' },
        { code: 'CO-HUI-GIG', name: 'Gigante' },
        { code: 'CO-HUI-PAL', name: 'Pitalito' },
      ],
    },
    {
      code: 'CO-LAG', name: 'La Guajira',
      communes: [
        { code: 'CO-LAG-RIO', name: 'Riohacha' },
        { code: 'CO-LAG-MAI', name: 'Maicao' },
      ],
    },
    {
      code: 'CO-MAG', name: 'Magdalena',
      communes: [
        { code: 'CO-MAG-SAN', name: 'Santa Marta' },
        { code: 'CO-MAG-CIE', name: 'Ciénaga' },
      ],
    },
    {
      code: 'CO-MET', name: 'Meta',
      communes: [
        { code: 'CO-MET-VIL', name: 'Villavicencio' },
        { code: 'CO-MET-ACO', name: 'Acacías' },
      ],
    },
    {
      code: 'CO-NAR', name: 'Nariño',
      communes: [
        { code: 'CO-NAR-PAS', name: 'Pasto' },
        { code: 'CO-NAR-TUM', name: 'Tumaco' },
      ],
    },
    {
      code: 'CO-NOR', name: 'Norte de Santander',
      communes: [
        { code: 'CO-NOR-CUC', name: 'Cúcuta' },
        { code: 'CO-NOR-OCA', name: 'Ocaña' },
      ],
    },
    {
      code: 'CO-PUT', name: 'Putumayo',
      communes: [
        { code: 'CO-PUT-MOC', name: 'Mocoa' },
        { code: 'CO-PUT-PTO', name: 'Puerto Asís' },
      ],
    },
    {
      code: 'CO-QUI', name: 'Quindío',
      communes: [
        { code: 'CO-QUI-ARM', name: 'Armenia' },
        { code: 'CO-QUI-CAL', name: 'Calarcá' },
      ],
    },
    {
      code: 'CO-RIS', name: 'Risaralda',
      communes: [
        { code: 'CO-RIS-PER', name: 'Pereira' },
        { code: 'CO-RIS-DOS', name: 'Dosquebradas' },
        { code: 'CO-RIS-SAN', name: 'Santa Rosa de Cabal' },
      ],
    },
    {
      code: 'CO-SAN', name: 'Santander',
      communes: [
        { code: 'CO-SAN-BUC', name: 'Bucaramanga' },
        { code: 'CO-SAN-FLO', name: 'Floridablanca' },
        { code: 'CO-SAN-GIR', name: 'Girón' },
        { code: 'CO-SAN-PIE', name: 'Piedecuesta' },
        { code: 'CO-SAN-BAR', name: 'Barrancabermeja' },
      ],
    },
    {
      code: 'CO-SUC', name: 'Sucre',
      communes: [
        { code: 'CO-SUC-SIN', name: 'Sincelejo' },
        { code: 'CO-SUC-COV', name: 'Corozal' },
      ],
    },
    {
      code: 'CO-TOL', name: 'Tolima',
      communes: [
        { code: 'CO-TOL-IBA', name: 'Ibagué' },
        { code: 'CO-TOL-ESP', name: 'Espinal' },
        { code: 'CO-TOL-MEL', name: 'Melgar' },
      ],
    },
    {
      code: 'CO-VAC', name: 'Valle del Cauca',
      communes: [
        { code: 'CO-VAC-CAL', name: 'Cali' },
        { code: 'CO-VAC-BUE', name: 'Buenaventura' },
        { code: 'CO-VAC-CAR', name: 'Cartago' },
        { code: 'CO-VAC-PAL', name: 'Palmira' },
        { code: 'CO-VAC-TUL', name: 'Tuluá' },
        { code: 'CO-VAC-BUG', name: 'Buenaventura' },
      ],
    },
  ],

  // ─── BRASIL — 27 estados ──────────────────────────────────────────────────
  BR: [
    {
      code: 'BR-AC', name: 'Acre',
      communes: [
        { code: 'BR-AC-RBR', name: 'Rio Branco' },
        { code: 'BR-AC-CRU', name: 'Cruzeiro do Sul' },
      ],
    },
    {
      code: 'BR-AL', name: 'Alagoas',
      communes: [
        { code: 'BR-AL-MAC', name: 'Maceió' },
        { code: 'BR-AL-ARA', name: 'Arapiraca' },
      ],
    },
    {
      code: 'BR-AP', name: 'Amapá',
      communes: [
        { code: 'BR-AP-MAC', name: 'Macapá' },
        { code: 'BR-AP-SAN', name: 'Santana' },
      ],
    },
    {
      code: 'BR-AM', name: 'Amazonas',
      communes: [
        { code: 'BR-AM-MAN', name: 'Manaus' },
        { code: 'BR-AM-PAR', name: 'Parintins' },
        { code: 'BR-AM-ITA', name: 'Itacoatiara' },
      ],
    },
    {
      code: 'BR-BA', name: 'Bahia',
      communes: [
        { code: 'BR-BA-SSA', name: 'Salvador' },
        { code: 'BR-BA-FAI', name: 'Feira de Santana' },
        { code: 'BR-BA-VIC', name: 'Vitória da Conquista' },
        { code: 'BR-BA-CAM', name: 'Camaçari' },
        { code: 'BR-BA-ILH', name: 'Ilhéus' },
        { code: 'BR-BA-ITA', name: 'Itabuna' },
      ],
    },
    {
      code: 'BR-CE', name: 'Ceará',
      communes: [
        { code: 'BR-CE-FOR', name: 'Fortaleza' },
        { code: 'BR-CE-CAU', name: 'Caucaia' },
        { code: 'BR-CE-JUA', name: 'Juazeiro do Norte' },
        { code: 'BR-CE-MAR', name: 'Maracanaú' },
      ],
    },
    {
      code: 'BR-DF', name: 'Distrito Federal',
      communes: [
        { code: 'BR-DF-BSB', name: 'Brasília' },
        { code: 'BR-DF-TGU', name: 'Taguatinga' },
        { code: 'BR-DF-CIL', name: 'Ceilândia' },
      ],
    },
    {
      code: 'BR-ES', name: 'Espírito Santo',
      communes: [
        { code: 'BR-ES-VIX', name: 'Vitória' },
        { code: 'BR-ES-CAR', name: 'Cariacica' },
        { code: 'BR-ES-SER', name: 'Serra' },
        { code: 'BR-ES-VVH', name: 'Vila Velha' },
      ],
    },
    {
      code: 'BR-GO', name: 'Goiás',
      communes: [
        { code: 'BR-GO-GOI', name: 'Goiânia' },
        { code: 'BR-GO-APO', name: 'Aparecida de Goiânia' },
        { code: 'BR-GO-ANA', name: 'Anápolis' },
      ],
    },
    {
      code: 'BR-MA', name: 'Maranhão',
      communes: [
        { code: 'BR-MA-SLZ', name: 'São Luís' },
        { code: 'BR-MA-TER', name: 'Teresina' },
        { code: 'BR-MA-IMP', name: 'Imperatriz' },
      ],
    },
    {
      code: 'BR-MT', name: 'Mato Grosso',
      communes: [
        { code: 'BR-MT-CGB', name: 'Cuiabá' },
        { code: 'BR-MT-VGG', name: 'Várzea Grande' },
        { code: 'BR-MT-RON', name: 'Rondonópolis' },
      ],
    },
    {
      code: 'BR-MS', name: 'Mato Grosso do Sul',
      communes: [
        { code: 'BR-MS-CGR', name: 'Campo Grande' },
        { code: 'BR-MS-DOU', name: 'Dourados' },
        { code: 'BR-MS-TRS', name: 'Três Lagoas' },
      ],
    },
    {
      code: 'BR-MG', name: 'Minas Gerais',
      communes: [
        { code: 'BR-MG-BHZ', name: 'Belo Horizonte' },
        { code: 'BR-MG-UDI', name: 'Uberlândia' },
        { code: 'BR-MG-CON', name: 'Contagem' },
        { code: 'BR-MG-JUI', name: 'Juiz de Fora' },
        { code: 'BR-MG-BET', name: 'Betim' },
        { code: 'BR-MG-MON', name: 'Montes Claros' },
        { code: 'BR-MG-UBE', name: 'Uberaba' },
      ],
    },
    {
      code: 'BR-PA', name: 'Pará',
      communes: [
        { code: 'BR-PA-BEL', name: 'Belém' },
        { code: 'BR-PA-ANA', name: 'Ananindeua' },
        { code: 'BR-PA-SAN', name: 'Santarém' },
        { code: 'BR-PA-MAR', name: 'Marabá' },
      ],
    },
    {
      code: 'BR-PB', name: 'Paraíba',
      communes: [
        { code: 'BR-PB-JPA', name: 'João Pessoa' },
        { code: 'BR-PB-CAM', name: 'Campina Grande' },
      ],
    },
    {
      code: 'BR-PR', name: 'Paraná',
      communes: [
        { code: 'BR-PR-CWB', name: 'Curitiba' },
        { code: 'BR-PR-LON', name: 'Londrina' },
        { code: 'BR-PR-MAR', name: 'Maringá' },
        { code: 'BR-PR-FOZ', name: 'Foz do Iguaçu' },
        { code: 'BR-PR-POA', name: 'Ponta Grossa' },
        { code: 'BR-PR-CAS', name: 'Cascavel' },
      ],
    },
    {
      code: 'BR-PE', name: 'Pernambuco',
      communes: [
        { code: 'BR-PE-REC', name: 'Recife' },
        { code: 'BR-PE-CAA', name: 'Caruaru' },
        { code: 'BR-PE-OLI', name: 'Olinda' },
        { code: 'BR-PE-CAB', name: 'Cabo de Santo Agostinho' },
        { code: 'BR-PE-PAU', name: 'Paulista' },
      ],
    },
    {
      code: 'BR-PI', name: 'Piauí',
      communes: [
        { code: 'BR-PI-THE', name: 'Teresina' },
        { code: 'BR-PI-PAR', name: 'Parnaíba' },
      ],
    },
    {
      code: 'BR-RJ', name: 'Rio de Janeiro',
      communes: [
        { code: 'BR-RJ-RIO', name: 'Rio de Janeiro' },
        { code: 'BR-RJ-SGA', name: 'São Gonçalo' },
        { code: 'BR-RJ-DUQ', name: 'Duque de Caxias' },
        { code: 'BR-RJ-NOV', name: 'Nova Iguaçu' },
        { code: 'BR-RJ-BEL', name: 'Belford Roxo' },
        { code: 'BR-RJ-NIT', name: 'Niterói' },
        { code: 'BR-RJ-CAM', name: 'Campos dos Goytacazes' },
        { code: 'BR-RJ-PET', name: 'Petrópolis' },
      ],
    },
    {
      code: 'BR-RN', name: 'Rio Grande do Norte',
      communes: [
        { code: 'BR-RN-NAT', name: 'Natal' },
        { code: 'BR-RN-MOS', name: 'Mossoró' },
      ],
    },
    {
      code: 'BR-RS', name: 'Rio Grande do Sul',
      communes: [
        { code: 'BR-RS-POA', name: 'Porto Alegre' },
        { code: 'BR-RS-CAN', name: 'Canoas' },
        { code: 'BR-RS-GRA', name: 'Gravataí' },
        { code: 'BR-RS-VIA', name: 'Viamão' },
        { code: 'BR-RS-CAX', name: 'Caxias do Sul' },
        { code: 'BR-RS-PEL', name: 'Pelotas' },
        { code: 'BR-RS-SAN', name: 'Santa Maria' },
      ],
    },
    {
      code: 'BR-RO', name: 'Rondônia',
      communes: [
        { code: 'BR-RO-PVH', name: 'Porto Velho' },
        { code: 'BR-RO-JIN', name: 'Ji-Paraná' },
      ],
    },
    {
      code: 'BR-RR', name: 'Roraima',
      communes: [
        { code: 'BR-RR-BVB', name: 'Boa Vista' },
        { code: 'BR-RR-ROC', name: 'Rorainópolis' },
      ],
    },
    {
      code: 'BR-SC', name: 'Santa Catarina',
      communes: [
        { code: 'BR-SC-FLN', name: 'Florianópolis' },
        { code: 'BR-SC-JOI', name: 'Joinville' },
        { code: 'BR-SC-BLU', name: 'Blumenau' },
        { code: 'BR-SC-CRI', name: 'Criciúma' },
        { code: 'BR-SC-CHE', name: 'Chapecó' },
        { code: 'BR-SC-ITA', name: 'Itajaí' },
      ],
    },
    {
      code: 'BR-SP', name: 'São Paulo',
      communes: [
        { code: 'BR-SP-SAO', name: 'São Paulo' },
        { code: 'BR-SP-GUA', name: 'Guarulhos' },
        { code: 'BR-SP-CAM', name: 'Campinas' },
        { code: 'BR-SP-SBC', name: 'São Bernardo do Campo' },
        { code: 'BR-SP-SAN', name: 'Santo André' },
        { code: 'BR-SP-SJC', name: 'São José dos Campos' },
        { code: 'BR-SP-RIB', name: 'Ribeirão Preto' },
        { code: 'BR-SP-OSA', name: 'Osasco' },
        { code: 'BR-SP-SOC', name: 'Sorocaba' },
        { code: 'BR-SP-MPC', name: 'Mauá' },
        { code: 'BR-SP-SJR', name: 'São José do Rio Preto' },
      ],
    },
    {
      code: 'BR-SE', name: 'Sergipe',
      communes: [
        { code: 'BR-SE-AJU', name: 'Aracaju' },
        { code: 'BR-SE-LAR', name: 'Lagarto' },
      ],
    },
    {
      code: 'BR-TO', name: 'Tocantins',
      communes: [
        { code: 'BR-TO-PAL', name: 'Palmas' },
        { code: 'BR-TO-ARA', name: 'Araguaína' },
      ],
    },
  ],

  // ─── PERÚ — 25 regiones ───────────────────────────────────────────────────
  PE: [
    { code: 'PE-AMA', name: 'Amazonas', communes: [{ code: 'PE-AMA-CHA', name: 'Chachapoyas' }, { code: 'PE-AMA-BAG', name: 'Bagua' }] },
    { code: 'PE-ANC', name: 'Áncash', communes: [{ code: 'PE-ANC-HUA', name: 'Huaraz' }, { code: 'PE-ANC-CHI', name: 'Chimbote' }] },
    { code: 'PE-APU', name: 'Apurímac', communes: [{ code: 'PE-APU-ABA', name: 'Abancay' }, { code: 'PE-APU-AND', name: 'Andahuaylas' }] },
    { code: 'PE-ARE', name: 'Arequipa', communes: [{ code: 'PE-ARE-ARE', name: 'Arequipa' }, { code: 'PE-ARE-CAM', name: 'Camaná' }] },
    { code: 'PE-AYA', name: 'Ayacucho', communes: [{ code: 'PE-AYA-AYA', name: 'Ayacucho' }, { code: 'PE-AYA-HUA', name: 'Huanta' }] },
    { code: 'PE-CAJ', name: 'Cajamarca', communes: [{ code: 'PE-CAJ-CAJ', name: 'Cajamarca' }, { code: 'PE-CAJ-JAE', name: 'Jaén' }] },
    { code: 'PE-CAL', name: 'Callao', communes: [{ code: 'PE-CAL-CAL', name: 'Callao' }, { code: 'PE-CAL-BEL', name: 'Bellavista' }] },
    { code: 'PE-CUS', name: 'Cusco', communes: [{ code: 'PE-CUS-CUS', name: 'Cusco' }, { code: 'PE-CUS-SAN', name: 'San Jerónimo' }] },
    { code: 'PE-HUA', name: 'Huancavelica', communes: [{ code: 'PE-HUA-HUA', name: 'Huancavelica' }, { code: 'PE-HUA-HAN', name: 'Huancayo' }] },
    { code: 'PE-HUC', name: 'Huánuco', communes: [{ code: 'PE-HUC-HUA', name: 'Huánuco' }, { code: 'PE-HUC-TIN', name: 'Tingo María' }] },
    { code: 'PE-ICA', name: 'Ica', communes: [{ code: 'PE-ICA-ICA', name: 'Ica' }, { code: 'PE-ICA-NAS', name: 'Nasca' }] },
    { code: 'PE-JUN', name: 'Junín', communes: [{ code: 'PE-JUN-HUC', name: 'Huancayo' }, { code: 'PE-JUN-TAR', name: 'Tarma' }] },
    { code: 'PE-LAL', name: 'La Libertad', communes: [{ code: 'PE-LAL-TRU', name: 'Trujillo' }, { code: 'PE-LAL-CHE', name: 'Chepén' }] },
    { code: 'PE-LAM', name: 'Lambayeque', communes: [{ code: 'PE-LAM-CHI', name: 'Chiclayo' }, { code: 'PE-LAM-LAM', name: 'Lambayeque' }] },
    { code: 'PE-LIM', name: 'Lima', communes: [{ code: 'PE-LIM-LIM', name: 'Lima' }, { code: 'PE-LIM-SJL', name: 'San Juan de Lurigancho' }, { code: 'PE-LIM-ATE', name: 'Ate' }, { code: 'PE-LIM-MIR', name: 'Miraflores' }, { code: 'PE-LIM-SUR', name: 'San Borja' }] },
    { code: 'PE-LOR', name: 'Loreto', communes: [{ code: 'PE-LOR-IQU', name: 'Iquitos' }, { code: 'PE-LOR-YUR', name: 'Yurimaguas' }] },
    { code: 'PE-MDD', name: 'Madre de Dios', communes: [{ code: 'PE-MDD-PUE', name: 'Puerto Maldonado' }, { code: 'PE-MDD-TAM', name: 'Tambopata' }] },
    { code: 'PE-MOQ', name: 'Moquegua', communes: [{ code: 'PE-MOQ-MOQ', name: 'Moquegua' }, { code: 'PE-MOQ-ILO', name: 'Ilo' }] },
    { code: 'PE-PAS', name: 'Pasco', communes: [{ code: 'PE-PAS-CER', name: 'Cerro de Pasco' }, { code: 'PE-PAS-OXA', name: 'Oxapampa' }] },
    { code: 'PE-PIU', name: 'Piura', communes: [{ code: 'PE-PIU-PIU', name: 'Piura' }, { code: 'PE-PIU-PAI', name: 'Paita' }, { code: 'PE-PIU-TRU', name: 'Sullana' }] },
    { code: 'PE-PUN', name: 'Puno', communes: [{ code: 'PE-PUN-PUN', name: 'Puno' }, { code: 'PE-PUN-JUL', name: 'Juliaca' }] },
    { code: 'PE-SAM', name: 'San Martín', communes: [{ code: 'PE-SAM-TAR', name: 'Tarapoto' }, { code: 'PE-SAM-MOY', name: 'Moyobamba' }] },
    { code: 'PE-TAC', name: 'Tacna', communes: [{ code: 'PE-TAC-TAC', name: 'Tacna' }, { code: 'PE-TAC-TAC2', name: 'Gregorio Albarracín' }] },
    { code: 'PE-TUM', name: 'Tumbes', communes: [{ code: 'PE-TUM-TUM', name: 'Tumbes' }, { code: 'PE-TUM-ZOR', name: 'Zarumilla' }] },
    { code: 'PE-UCA', name: 'Ucayali', communes: [{ code: 'PE-UCA-PUC', name: 'Pucallpa' }, { code: 'PE-UCA-COO', name: 'Coronel Portillo' }] },
  ],

  // ─── BOLIVIA — 9 departamentos ────────────────────────────────────────────
  BO: [
    { code: 'BO-B', name: 'Beni', communes: [{ code: 'BO-B-TRI', name: 'Trinidad' }, { code: 'BO-B-RIB', name: 'Riberalta' }] },
    { code: 'BO-C', name: 'Cochabamba', communes: [{ code: 'BO-C-COC', name: 'Cochabamba' }, { code: 'BO-C-STA', name: 'Sacaba' }, { code: 'BO-C-QUI', name: 'Quillacollo' }] },
    { code: 'BO-H', name: 'Chuquisaca', communes: [{ code: 'BO-H-SUC', name: 'Sucre' }, { code: 'BO-H-CAM', name: 'Camiri' }] },
    { code: 'BO-L', name: 'La Paz', communes: [{ code: 'BO-L-LAP', name: 'La Paz' }, { code: 'BO-L-ELT', name: 'El Alto' }, { code: 'BO-L-VIA', name: 'Viacha' }] },
    { code: 'BO-N', name: 'Pando', communes: [{ code: 'BO-N-COB', name: 'Cobija' }, { code: 'BO-N-POE', name: 'Porvenir' }] },
    { code: 'BO-O', name: 'Oruro', communes: [{ code: 'BO-O-ORU', name: 'Oruro' }, { code: 'BO-O-HUO', name: 'Huanuni' }] },
    { code: 'BO-P', name: 'Potosí', communes: [{ code: 'BO-P-POT', name: 'Potosí' }, { code: 'BO-P-LLI', name: 'Llallagua' }] },
    { code: 'BO-S', name: 'Santa Cruz', communes: [{ code: 'BO-S-SCZ', name: 'Santa Cruz de la Sierra' }, { code: 'BO-S-MON', name: 'Montero' }, { code: 'BO-S-WAR', name: 'Warnes' }, { code: 'BO-S-COT', name: 'Cotoca' }] },
    { code: 'BO-T', name: 'Tarija', communes: [{ code: 'BO-T-TAR', name: 'Tarija' }, { code: 'BO-T-YAC', name: 'Yacuiba' }] },
  ],

  // ─── URUGUAY — 19 departamentos ──────────────────────────────────────────
  UY: [
    { code: 'UY-AR', name: 'Artigas', communes: [{ code: 'UY-AR-ART', name: 'Artigas' }, { code: 'UY-AR-BEL', name: 'Bella Unión' }] },
    { code: 'UY-CA', name: 'Canelones', communes: [{ code: 'UY-CA-CAN', name: 'Canelones' }, { code: 'UY-CA-CIU', name: 'Ciudad de la Costa' }, { code: 'UY-CA-LAS', name: 'Las Piedras' }, { code: 'UY-CA-PAD', name: 'Pando' }] },
    { code: 'UY-CL', name: 'Cerro Largo', communes: [{ code: 'UY-CL-MEL', name: 'Melo' }, { code: 'UY-CL-RIO', name: 'Río Branco' }] },
    { code: 'UY-CO', name: 'Colonia', communes: [{ code: 'UY-CO-COL', name: 'Colonia del Sacramento' }, { code: 'UY-CO-CAR', name: 'Carmelo' }] },
    { code: 'UY-DU', name: 'Durazno', communes: [{ code: 'UY-DU-DUR', name: 'Durazno' }, { code: 'UY-DU-SAR', name: 'Sarandí del Yí' }] },
    { code: 'UY-FS', name: 'Flores', communes: [{ code: 'UY-FS-TRI', name: 'Trinidad' }] },
    { code: 'UY-FD', name: 'Florida', communes: [{ code: 'UY-FD-FLO', name: 'Florida' }, { code: 'UY-FD-CAS', name: 'Casupá' }] },
    { code: 'UY-LA', name: 'Lavalleja', communes: [{ code: 'UY-LA-MIN', name: 'Minas' }, { code: 'UY-LA-SOL', name: 'Solís de Mataojo' }] },
    { code: 'UY-MA', name: 'Maldonado', communes: [{ code: 'UY-MA-MAL', name: 'Maldonado' }, { code: 'UY-MA-PUN', name: 'Punta del Este' }, { code: 'UY-MA-SAN', name: 'San Carlos' }] },
    { code: 'UY-MO', name: 'Montevideo', communes: [{ code: 'UY-MO-MVD', name: 'Montevideo' }, { code: 'UY-MO-CEN', name: 'Centro' }, { code: 'UY-MO-MIS', name: 'Missile' }, { code: 'UY-MO-CAR', name: 'Carrasco' }, { code: 'UY-MO-POC', name: 'Pocitos' }] },
    { code: 'UY-PA', name: 'Paysandú', communes: [{ code: 'UY-PA-PAY', name: 'Paysandú' }, { code: 'UY-PA-GUA', name: 'Guichón' }] },
    { code: 'UY-RN', name: 'Río Negro', communes: [{ code: 'UY-RN-FAY', name: 'Fray Bentos' }, { code: 'UY-RN-YOU', name: 'Young' }] },
    { code: 'UY-RV', name: 'Rivera', communes: [{ code: 'UY-RV-RIV', name: 'Rivera' }, { code: 'UY-RV-MAN', name: 'Mansavillagra' }] },
    { code: 'UY-RO', name: 'Rocha', communes: [{ code: 'UY-RO-ROC', name: 'Rocha' }, { code: 'UY-RO-LAP', name: 'La Paloma' }] },
    { code: 'UY-SA', name: 'Salto', communes: [{ code: 'UY-SA-SAL', name: 'Salto' }, { code: 'UY-SA-BEL', name: 'Belén' }] },
    { code: 'UY-SJ', name: 'San José', communes: [{ code: 'UY-SJ-SJM', name: 'San José de Mayo' }, { code: 'UY-SJ-OCT', name: '25 de Mayo' }] },
    { code: 'UY-SO', name: 'Soriano', communes: [{ code: 'UY-SO-MER', name: 'Mercedes' }, { code: 'UY-SO-DOL', name: 'Dolores' }] },
    { code: 'UY-TA', name: 'Tacuarembó', communes: [{ code: 'UY-TA-TAC', name: 'Tacuarembó' }, { code: 'UY-TA-SAR', name: 'Sarandí Grande' }] },
    { code: 'UY-TT', name: 'Treinta y Tres', communes: [{ code: 'UY-TT-TYT', name: 'Treinta y Tres' }, { code: 'UY-TT-VER', name: 'Vergara' }] },
  ],

  // ─── ECUADOR — 24 provincias ─────────────────────────────────────────────
  EC: [
    { code: 'EC-A', name: 'Azuay', communes: [{ code: 'EC-A-CUE', name: 'Cuenca' }, { code: 'EC-A-GUA', name: 'Gualaceo' }] },
    { code: 'EC-B', name: 'Bolívar', communes: [{ code: 'EC-B-GUA', name: 'Guaranda' }] },
    { code: 'EC-F', name: 'Cañar', communes: [{ code: 'EC-F-AZO', name: 'Azogues' }, { code: 'EC-F-CAÑ', name: 'Cañar' }] },
    { code: 'EC-C', name: 'Carchi', communes: [{ code: 'EC-C-TUL', name: 'Tulcán' }] },
    { code: 'EC-H', name: 'Chimborazo', communes: [{ code: 'EC-H-RIO', name: 'Riobamba' }, { code: 'EC-H-ALU', name: 'Alausí' }] },
    { code: 'EC-X', name: 'Cotopaxi', communes: [{ code: 'EC-X-LAT', name: 'Latacunga' }, { code: 'EC-X-SAL', name: 'Salcedo' }] },
    { code: 'EC-O', name: 'El Oro', communes: [{ code: 'EC-O-MAC', name: 'Machala' }, { code: 'EC-O-HUA', name: 'Huaquillas' }, { code: 'EC-O-SAR', name: 'Santa Rosa' }] },
    { code: 'EC-E', name: 'Esmeraldas', communes: [{ code: 'EC-E-ESM', name: 'Esmeraldas' }, { code: 'EC-E-QUI', name: 'Quinindé' }] },
    { code: 'EC-W', name: 'Galápagos', communes: [{ code: 'EC-W-PBA', name: 'Puerto Baquerizo Moreno' }] },
    { code: 'EC-G', name: 'Guayas', communes: [{ code: 'EC-G-GUY', name: 'Guayaquil' }, { code: 'EC-G-SAM', name: 'Samborondón' }, { code: 'EC-G-MIL', name: 'Milagro' }, { code: 'EC-G-DUR', name: 'Durán' }] },
    { code: 'EC-I', name: 'Imbabura', communes: [{ code: 'EC-I-IBA', name: 'Ibarra' }, { code: 'EC-I-OTA', name: 'Otavalo' }, { code: 'EC-I-COT', name: 'Cotacachi' }] },
    { code: 'EC-L', name: 'Loja', communes: [{ code: 'EC-L-LOJ', name: 'Loja' }, { code: 'EC-L-CAT', name: 'Catamayo' }] },
    { code: 'EC-R', name: 'Los Ríos', communes: [{ code: 'EC-R-BAB', name: 'Babahoyo' }, { code: 'EC-R-QUE', name: 'Quevedo' }, { code: 'EC-R-VIN', name: 'Vinces' }] },
    { code: 'EC-M', name: 'Manabí', communes: [{ code: 'EC-M-POR', name: 'Portoviejo' }, { code: 'EC-M-MAN', name: 'Manta' }, { code: 'EC-M-MON', name: 'Montecristi' }] },
    { code: 'EC-S', name: 'Morona Santiago', communes: [{ code: 'EC-S-MAC', name: 'Macas' }] },
    { code: 'EC-N', name: 'Napo', communes: [{ code: 'EC-N-TEN', name: 'Tena' }] },
    { code: 'EC-D', name: 'Orellana', communes: [{ code: 'EC-D-PFC', name: 'Puerto Francisco de Orellana' }] },
    { code: 'EC-Y', name: 'Pastaza', communes: [{ code: 'EC-Y-PUY', name: 'Puyo' }] },
    { code: 'EC-P', name: 'Pichincha', communes: [{ code: 'EC-P-QUI', name: 'Quito' }, { code: 'EC-P-RUM', name: 'Rumiñahui' }, { code: 'EC-P-CAY', name: 'Cayambe' }, { code: 'EC-P-PED', name: 'Pedro Moncayo' }] },
    { code: 'EC-SE', name: 'Santa Elena', communes: [{ code: 'EC-SE-SAE', name: 'Santa Elena' }, { code: 'EC-SE-SAL', name: 'Salinas' }] },
    { code: 'EC-SD', name: 'Santo Domingo de los Tsáchilas', communes: [{ code: 'EC-SD-SDT', name: 'Santo Domingo' }] },
    { code: 'EC-U', name: 'Sucumbíos', communes: [{ code: 'EC-U-NLO', name: 'Nueva Loja' }] },
    { code: 'EC-T', name: 'Tungurahua', communes: [{ code: 'EC-T-AMB', name: 'Ambato' }, { code: 'EC-T-BAÑ', name: 'Baños de Agua Santa' }] },
    { code: 'EC-Z', name: 'Zamora Chinchipe', communes: [{ code: 'EC-Z-ZAM', name: 'Zamora' }] },
  ],

  // ─── MÉXICO — 32 estados ──────────────────────────────────────────────────
  MX: [
    { code: 'MX-AGU', name: 'Aguascalientes', communes: [{ code: 'MX-AGU-AGU', name: 'Aguascalientes' }, { code: 'MX-AGU-RIN', name: 'Rincón de Romos' }] },
    { code: 'MX-BCN', name: 'Baja California', communes: [{ code: 'MX-BCN-TIJ', name: 'Tijuana' }, { code: 'MX-BCN-MXL', name: 'Mexicali' }, { code: 'MX-BCN-ENS', name: 'Ensenada' }, { code: 'MX-BCN-ROS', name: 'Rosarito' }] },
    { code: 'MX-BCS', name: 'Baja California Sur', communes: [{ code: 'MX-BCS-LPA', name: 'La Paz' }, { code: 'MX-BCS-SJC', name: 'San José del Cabo' }, { code: 'MX-BCS-CAB', name: 'Cabo San Lucas' }] },
    { code: 'MX-CAM', name: 'Campeche', communes: [{ code: 'MX-CAM-CAM', name: 'Campeche' }, { code: 'MX-CAM-CIU', name: 'Ciudad del Carmen' }] },
    { code: 'MX-CHH', name: 'Chihuahua', communes: [{ code: 'MX-CHH-CHH', name: 'Chihuahua' }, { code: 'MX-CHH-JUA', name: 'Ciudad Juárez' }, { code: 'MX-CHH-DER', name: 'Delicias' }] },
    { code: 'MX-CHP', name: 'Chiapas', communes: [{ code: 'MX-CHP-TGZ', name: 'Tuxtla Gutiérrez' }, { code: 'MX-CHP-SCI', name: 'San Cristóbal de las Casas' }, { code: 'MX-CHP-TAP', name: 'Tapachula' }] },
    { code: 'MX-CMX', name: 'Ciudad de México', communes: [{ code: 'MX-CMX-CUH', name: 'Cuauhtémoc' }, { code: 'MX-CMX-IZT', name: 'Iztapalapa' }, { code: 'MX-CMX-GAM', name: 'Gustavo A. Madero' }, { code: 'MX-CMX-ALV', name: 'Álvaro Obregón' }, { code: 'MX-CMX-TLA', name: 'Tlalpan' }, { code: 'MX-CMX-COY', name: 'Coyoacán' }, { code: 'MX-CMX-BEN', name: 'Benito Juárez' }, { code: 'MX-CMX-MIG', name: 'Miguel Hidalgo' }] },
    { code: 'MX-COA', name: 'Coahuila', communes: [{ code: 'MX-COA-SAL', name: 'Saltillo' }, { code: 'MX-COA-TOR', name: 'Torreón' }, { code: 'MX-COA-MON', name: 'Monclova' }] },
    { code: 'MX-COL', name: 'Colima', communes: [{ code: 'MX-COL-COL', name: 'Colima' }, { code: 'MX-COL-MAN', name: 'Manzanillo' }] },
    { code: 'MX-DUR', name: 'Durango', communes: [{ code: 'MX-DUR-DGO', name: 'Durango' }, { code: 'MX-DUR-GOM', name: 'Gómez Palacio' }] },
    { code: 'MX-GRO', name: 'Guerrero', communes: [{ code: 'MX-GRO-ACA', name: 'Acapulco' }, { code: 'MX-GRO-CHI', name: 'Chilpancingo' }, { code: 'MX-GRO-ZIH', name: 'Zihuatanejo' }] },
    { code: 'MX-GUA', name: 'Guanajuato', communes: [{ code: 'MX-GUA-LEO', name: 'León' }, { code: 'MX-GUA-GUA', name: 'Guanajuato' }, { code: 'MX-GUA-IRA', name: 'Irapuato' }, { code: 'MX-GUA-CEL', name: 'Celaya' }] },
    { code: 'MX-HID', name: 'Hidalgo', communes: [{ code: 'MX-HID-PAC', name: 'Pachuca' }, { code: 'MX-HID-TUL', name: 'Tulancingo' }] },
    { code: 'MX-JAL', name: 'Jalisco', communes: [{ code: 'MX-JAL-GDL', name: 'Guadalajara' }, { code: 'MX-JAL-ZAP', name: 'Zapopan' }, { code: 'MX-JAL-TLA', name: 'Tlaquepaque' }, { code: 'MX-JAL-TON', name: 'Tonalá' }, { code: 'MX-JAL-PUR', name: 'Puerto Vallarta' }] },
    { code: 'MX-MEX', name: 'Estado de México', communes: [{ code: 'MX-MEX-ECO', name: 'Ecatepec' }, { code: 'MX-MEX-TLA', name: 'Toluca' }, { code: 'MX-MEX-NEZ', name: 'Nezahualcóyotl' }, { code: 'MX-MEX-NAU', name: 'Naucalpan' }, { code: 'MX-MEX-TLN', name: 'Tlalnepantla' }] },
    { code: 'MX-MIC', name: 'Michoacán', communes: [{ code: 'MX-MIC-MOR', name: 'Morelia' }, { code: 'MX-MIC-LAZ', name: 'Lázaro Cárdenas' }, { code: 'MX-MIC-ZAM', name: 'Zamora' }] },
    { code: 'MX-MOR', name: 'Morelos', communes: [{ code: 'MX-MOR-CUE', name: 'Cuernavaca' }, { code: 'MX-MOR-JIM', name: 'Jiutepec' }] },
    { code: 'MX-NAY', name: 'Nayarit', communes: [{ code: 'MX-NAY-TEP', name: 'Tepic' }, { code: 'MX-NAY-BVA', name: 'Bahía de Banderas' }] },
    { code: 'MX-NLE', name: 'Nuevo León', communes: [{ code: 'MX-NLE-MTY', name: 'Monterrey' }, { code: 'MX-NLE-GAR', name: 'Garza García' }, { code: 'MX-NLE-SAN', name: 'San Nicolás' }, { code: 'MX-NLE-APO', name: 'Apodaca' }, { code: 'MX-NLE-SCA', name: 'Santa Catarina' }] },
    { code: 'MX-OAX', name: 'Oaxaca', communes: [{ code: 'MX-OAX-OAX', name: 'Oaxaca de Juárez' }, { code: 'MX-OAX-SAL', name: 'Salina Cruz' }] },
    { code: 'MX-PUE', name: 'Puebla', communes: [{ code: 'MX-PUE-PUE', name: 'Puebla' }, { code: 'MX-PUE-TEH', name: 'Tehuacán' }, { code: 'MX-PUE-SAN', name: 'San Andrés Cholula' }] },
    { code: 'MX-QUE', name: 'Querétaro', communes: [{ code: 'MX-QUE-QRO', name: 'Querétaro' }, { code: 'MX-QUE-SJR', name: 'San Juan del Río' }] },
    { code: 'MX-ROO', name: 'Quintana Roo', communes: [{ code: 'MX-ROO-CUN', name: 'Cancún' }, { code: 'MX-ROO-PDC', name: 'Playa del Carmen' }, { code: 'MX-ROO-CHM', name: 'Chetumal' }] },
    { code: 'MX-SLP', name: 'San Luis Potosí', communes: [{ code: 'MX-SLP-SLP', name: 'San Luis Potosí' }, { code: 'MX-SLP-SOL', name: 'Soledad de Graciano' }] },
    { code: 'MX-SIN', name: 'Sinaloa', communes: [{ code: 'MX-SIN-CLN', name: 'Culiacán' }, { code: 'MX-SIN-MAZ', name: 'Mazatlán' }, { code: 'MX-SIN-AHM', name: 'Ahome' }] },
    { code: 'MX-SON', name: 'Sonora', communes: [{ code: 'MX-SON-HMO', name: 'Hermosillo' }, { code: 'MX-SON-CDO', name: 'Ciudad Obregón' }, { code: 'MX-SON-NOG', name: 'Nogales' }] },
    { code: 'MX-TAB', name: 'Tabasco', communes: [{ code: 'MX-TAB-VIL', name: 'Villahermosa' }, { code: 'MX-TAB-CAR', name: 'Cárdenas' }] },
    { code: 'MX-TAM', name: 'Tamaulipas', communes: [{ code: 'MX-TAM-REY', name: 'Reynosa' }, { code: 'MX-TAM-MAT', name: 'Matamoros' }, { code: 'MX-TAM-NLA', name: 'Nuevo Laredo' }, { code: 'MX-TAM-TAM', name: 'Tampico' }, { code: 'MX-TAM-VIC', name: 'Ciudad Victoria' }] },
    { code: 'MX-TLA', name: 'Tlaxcala', communes: [{ code: 'MX-TLA-TLA', name: 'Tlaxcala' }, { code: 'MX-TLA-API', name: 'Apizaco' }] },
    { code: 'MX-VER', name: 'Veracruz', communes: [{ code: 'MX-VER-VER', name: 'Veracruz' }, { code: 'MX-VER-XAL', name: 'Xalapa' }, { code: 'MX-VER-COA', name: 'Coatzacoalcos' }] },
    { code: 'MX-YUC', name: 'Yucatán', communes: [{ code: 'MX-YUC-MER', name: 'Mérida' }, { code: 'MX-YUC-VAL', name: 'Valladolid' }] },
    { code: 'MX-ZAC', name: 'Zacatecas', communes: [{ code: 'MX-ZAC-ZAC', name: 'Zacatecas' }, { code: 'MX-ZAC-FRE', name: 'Fresnillo' }] },
  ],
};
