/** Catálogo de tipos de evento para clinical_case_event.action */
export const CASE_EVENTS = {
  // Ciclo de vida del caso
  CREACION: 'CREACION',
  /** Alias canónico UCH core */
  CASO_CREADO: 'CASO_CREADO',
  /** Copia desde caso terminal (Crear copia). */
  CASO_COPIA: 'CASO_COPIA',
  PUBLICACION: 'PUBLICACION',
  CASO_PUBLICADO: 'CASO_PUBLICADO',
  PROPUESTA_RECIBIDA: 'PROPUESTA_RECIBIDA',
  REPUBLICACION: 'REPUBLICACION',
  RETIRO_PUBLICACION: 'RETIRO_PUBLICACION',
  CASO_ACTUALIZADO: 'CASO_ACTUALIZADO',

  // Flujo de ofertas
  OFERTA_RECIBIDA: 'OFERTA_RECIBIDA',
  OFERTA_ACEPTADA: 'OFERTA_ACEPTADA',
  OFERTA_RECHAZADA: 'OFERTA_RECHAZADA',
  OFERTA_RETIRADA: 'OFERTA_RETIRADA',
  PROPUESTA_ACEPTADA: 'PROPUESTA_ACEPTADA',
  OFERTA_GANADORA: 'OFERTA_GANADORA',
  OFERTA_NO_SELECCIONADA: 'OFERTA_NO_SELECCIONADA',
  INVITACION_ENVIADA: 'INVITACION_ENVIADA',
  INVITACION_RECIBIDA: 'INVITACION_RECIBIDA',
  INVITACION_EXPIRADA: 'INVITACION_EXPIRADA',
  /** Técnico envió cotización (visible técnico) */
  OFERTA_ENVIADA: 'OFERTA_ENVIADA',
  /** Técnico rechazó explícitamente su invitación (v5.0, visibleTo sistema; el dentista no lo ve) */
  OFERTA_RECHAZADA_POR_TECNICO: 'OFERTA_RECHAZADA_POR_TECNICO',
  /** Caso re-publicado tras sin_cotizaciones_fallo (v5.0) */
  CASO_REPUBLICADO: 'CASO_REPUBLICADO',
  CASO_SIN_OFERTAS_CERRADO: 'CASO_SIN_OFERTAS_CERRADO',
  OFERTAS_COMPARATIVAS_LISTAS: 'OFERTAS_COMPARATIVAS_LISTAS',
  CASO_OFERTAS_TODAS_RECHAZADAS: 'CASO_OFERTAS_TODAS_RECHAZADAS',
  PROPUESTA_EXPIRADA: 'PROPUESTA_EXPIRADA',

  /** Asignación directa (v5.9) */
  ASIGNACION_ENVIADA: 'ASIGNACION_ENVIADA',
  ASIGNACION_RECIBIDA: 'ASIGNACION_RECIBIDA',
  ASIGNACION_ACEPTADA: 'ASIGNACION_ACEPTADA',
  ASIGNACION_RECHAZADA: 'ASIGNACION_RECHAZADA',
  ASIGNACION_EXPIRADA: 'ASIGNACION_EXPIRADA',
  ASIGNACION_REASIGNADA: 'ASIGNACION_REASIGNADA',

  // Flujo de trabajo
  TRABAJO_INICIADO: 'TRABAJO_INICIADO',
  REVISION_ENVIADA: 'REVISION_ENVIADA',
  REVISION_SOLICITADA: 'REVISION_SOLICITADA',
  TRABAJO_APROBADO: 'TRABAJO_APROBADO',
  /** Calificación (CAD/CAM) que el dentista deja al técnico; queda reflejada en el UCH de ambos (técnico la ve enmascarada/anónima) y la ve el admin para arbitrar. */
  CALIFICACION_ENVIADA: 'CALIFICACION_ENVIADA',
  REANUDADO: 'REANUDADO',

  /** Mutuo acuerdo: pausa o cancelación aprobada */
  CASO_PAUSADO: 'CASO_PAUSADO',
  CASO_CANCELADO: 'CASO_CANCELADO',
  /** Solicitud de pausa/cancelación pendiente de respuesta */
  SOLICITUD_CAMBIO_FLUJO: 'SOLICITUD_CAMBIO_FLUJO',
  SOLICITUD_CAMBIO_FLUJO_RECHAZADA: 'SOLICITUD_CAMBIO_FLUJO_RECHAZADA',

  // Comunicación
  COMENTARIO_TECNICO: 'COMENTARIO_TECNICO',
} as const;

export type CaseEvent = typeof CASE_EVENTS[keyof typeof CASE_EVENTS];
